# Generated by Django 5.0.1 on 2024-01-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeDollar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='mxn_to_usd',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='usd_to_mxn',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
